version: "3.8"
services:
  vpn:
    container_name: vpn
    image: bubuntux/nordvpn:latest
    cap_add:
      - net_admin # required to modify network interfaces
      - sys_module # required for NordLynx
    restart: always
    devices:
      - /dev/net/tun
    environment:
      - USER=${VPN_USER} # vpn user, defined in .env
      - PASS=${VPN_PASSWORD} # vpn password, defined in .env
      - COUNTRY=${VPN_COUNTRY} # vpn country, defined in .env
      - NETWORK=${NETWORK} # local network mask, defined in .env
      - TECHNOLOGY=${VPN_TECHNOLOGY}
      - TZ=${TZ} # timezone, defined in .env
      - CATEGORY=${VPN_CATEGORY}
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
    ports:
      - 9091:9091 # Transmission web UI
      - 51413:51413 # Transmission bittorrent daemon
      - 51413:51413/udp # Transmission bittorrent daemon

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    depends_on:
      - vpn
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${CONFIG}/transmission:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    depends_on:
      - transmission
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG}/jackett:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    depends_on:
      - transmission
      - jackett
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/sonarr:/config # config files
      - ${ROOT}/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    depends_on:
      - transmission
      - jackett
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG}/radarr:/config # config files
      - ${ROOT}/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder
